### PR TITLE
Merge after validating Javadoc generation from Protelis

### PR DESCRIPTION
**Pull request by jakebeal**

### CODE REVIEW

**Comment by jakebeal** [comment]
@metaphori This fail for me with the following message:

````
 ./gradlew generateProtelisDoc

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '12.0.1'.
````

Can you please help debug?

**Comment by DanySK** [comment]
@metaphori @jakebeal this looks to me as Java 12 being used with a version of Gradle not supporting it. Does `./gradlew compileJava` work as expected?

**Comment by jakebeal** [comment]
Hmm... I don't know why gradle didn't upgrade itself correctly... I just tried again and it shifted to 5.5.1 and was able to produce docs.  The docs don't look like normal javadoc, though.  There's no frames and no formatting, just a list of packages, and when you click on a package a list of functions.

Maybe it's because this project doesn't really have proper JavaDoc information on its Protelis code... but that should still wind up with normal formatting, just less information, shouldn't it?

**Comment by DanySK** [comment]
You seem to be describing the default output of Dokka:
image

There are a few limitations that @metaphori should document (if they are not yet):
* due to Kotlin/dokka#294, generation of Javadoc-formatted documentation requires Java 8. This will be solved as soon as Dokka is fixed.
* The tool defaults to the Java-like look, but if it detects a version of Java currently unsupported by Dokka, rather than failing produces KDoc-like pages. The amount of information is the same.
* I do not know which is the target JVM for P2Protelis, but I'd recommend testing in integration with all the supported JVMs, just like we do for Protelis itself, and pick a reference to be used to generate reports and documentation (in the case of Protelis, the latest OpenJDK 8 from AdoptOpenJDK).

**Comment by jakebeal** [comment]
Yes, that's what it looks like --- I guess we can declare this "good enough" for now then.

**Pull request merged**
